// Public marketing landing page shown at "/" for signed-out visitors.
// Authenticated users get the real app Home instead (see App.jsx RootEntry).
import { Link } from 'react-router-dom';
import {
  IoShirtOutline,
  IoCameraOutline,
  IoGridOutline,
  IoColorPaletteOutline,
  IoArrowForward,
  IoSparkles,
  IoCheckmarkCircle,
} from 'react-icons/io5';
import './Landing.css';

const FEATURES = [
  {
    icon: <IoShirtOutline />,
    title: 'Try Any Clothing',
    text: 'Upload any garment and see it worn instantly. Virtually try on outfits on AI models — no photoshoot, no fitting room.',
  },
  {
    icon: <IoCameraOutline />,
    title: 'Model Photoshoot',
    text: 'Generate studio-quality model photoshoots in seconds. Pick a model, a pose, and a scene — no camera or crew required.',
  },
  {
    icon: <IoGridOutline />,
    title: 'Create Catalog',
    text: 'Build full product catalogs at scale with consistent models, backgrounds, and lighting across every single shot.',
  },
  {
    icon: <IoColorPaletteOutline />,
    title: 'Branding Content',
    text: 'Produce on-brand marketing visuals and ad creatives tailored to your brand’s style, colors, and campaigns.',
  },
];

const STEPS = [
  { n: '1', title: 'Upload', text: 'Add your product, garment, or brand assets.' },
  { n: '2', title: 'Choose', text: 'Select a model, pose, scene, or catalog style.' },
  { n: '3', title: 'Generate', text: 'Get high-resolution, ready-to-use images instantly.' },
];

export default function Landing() {
  return (
    <div className="landing">
      {/* ── Nav ─────────────────────────────────────────────── */}
      <header className="landing-nav">
        <div className="landing-container landing-nav-inner">
          <a className="brand" href="/">
            <span className="brand-mark">
              <IoSparkles />
            </span>
            <span className="brand-name">BrandShoot&nbsp;AI</span>
          </a>
          <nav className="landing-nav-links">
            <a href="#features">Features</a>
            <a href="#how">How it works</a>
            <Link className="btn btn-ghost" to="/login">
              Login
            </Link>
          </nav>
        </div>
      </header>

      {/* ── Hero ────────────────────────────────────────────── */}
      <section className="hero">
        <div className="landing-container hero-inner">
          <span className="eyebrow">
            <IoSparkles /> AI-powered fashion studio
          </span>
          <h1 className="hero-title">
            Stunning product &amp; fashion shoots,
            <span className="grad-text"> generated by AI</span>
          </h1>
          <p className="hero-sub">
            BrandShoot AI turns a single photo into professional photoshoots.
            Try any clothing, create model shoots, build catalogs, and craft
            branding content — all without a studio.
          </p>
          <div className="hero-cta">
            <Link className="btn btn-primary btn-lg" to="/login">
              Login to get started <IoArrowForward />
            </Link>
            <a className="btn btn-outline btn-lg" href="#features">
              See features
            </a>
          </div>
          <ul className="hero-points">
            <li><IoCheckmarkCircle /> No camera or crew</li>
            <li><IoCheckmarkCircle /> Ready in seconds</li>
            <li><IoCheckmarkCircle /> Studio-quality results</li>
          </ul>
        </div>
        <div className="hero-glow" aria-hidden="true" />
      </section>

      {/* ── Features ────────────────────────────────────────── */}
      <section className="features" id="features">
        <div className="landing-container">
          <div className="section-head">
            <h2>Everything you need to create</h2>
            <p>Four powerful tools in one AI studio.</p>
          </div>
          <div className="feature-grid">
            {FEATURES.map((f) => (
              <article className="feature-card" key={f.title}>
                <div className="feature-icon">{f.icon}</div>
                <h3>{f.title}</h3>
                <p>{f.text}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── How it works ────────────────────────────────────── */}
      <section className="how" id="how">
        <div className="landing-container">
          <div className="section-head">
            <h2>How it works</h2>
            <p>From idea to finished shot in three steps.</p>
          </div>
          <div className="steps">
            {STEPS.map((s) => (
              <div className="step" key={s.n}>
                <span className="step-n">{s.n}</span>
                <h3>{s.title}</h3>
                <p>{s.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA band ────────────────────────────────────────── */}
      <section className="cta-band">
        <div className="landing-container cta-inner">
          <h2>Ready to create your first shoot?</h2>
          <p>Log in to start generating with BrandShoot AI.</p>
          <Link className="btn btn-primary btn-lg" to="/login">
            Login <IoArrowForward />
          </Link>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────────── */}
      <footer className="landing-footer">
        <div className="landing-container footer-inner">
          <a className="brand" href="/">
            <span className="brand-mark">
              <IoSparkles />
            </span>
            <span className="brand-name">BrandShoot&nbsp;AI</span>
          </a>
          <span className="footer-copy">
            © {new Date().getFullYear()} BrandShoot AI. All rights reserved.
          </span>
          <Link className="btn btn-ghost" to="/login">
            Login
          </Link>
        </div>
      </footer>
    </div>
  );
}
